name: accessors-rtd
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - packaging
  - importlib-metadata
  - sphinx<2
  - Pygments=2.3.1
  - setuptools=41.0.1
  - docutils=0.14
  - mock=1.0.1
  - pillow=5.4.1
  - commonmark=0.8.1
  - recommonmark=0.5.0
  - pip:
      - alabaster>=0.7,<0.8,!=0.7.5
      - sphinx-rtd-theme<0.5
      - readthedocs-sphinx-ext<1.1
